// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4579.testRobot2018.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc4579.testRobot2018.Robot;

/**
 *
 */
public class centerAuto extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public centerAuto() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    double speed = 0.0;
    int count = 0;
	int targetCount = 53275;
	int slowTargetCount = targetCount - (60 * 100);
	double increment = 0.005;

	double startTime;
	
	int runs = 0;
	int direction = 1;
	
    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    	setTimeout(30);
    	startTime = Timer.getFPGATimestamp();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	if(runs%2 == 0){
    		direction = 1;
    	}
    	else{
    		direction = -1;
    	}
    	count = Robot.measurement.getFlowMotionX();

    	System.out.print("Flow Motion X: ");
    	System.out.println(count);
    	
    	if (count > slowTargetCount) {
    		increment = -0.005;
    		System.out.println("*** Slowing...");
    	}
    	
    	speed = Math.max(.1, Math.min(0.3, speed + increment));
    	Robot.driveTrain.driveStraight(speed * direction);
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
    	if (count >= targetCount){
    		System.out.println("Target Reached ******");
    		runs++;
        	speed = 0.0;
        	increment = .005;
        	targetCount *= 2;
        	slowTargetCount = targetCount - (60 * 100);        	
    	}
    	return (isTimedOut() | count >= targetCount & runs > 5);
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    	Robot.driveTrain.stop();
    	System.out.println("Total Auto Time: " + (Timer.getFPGATimestamp() - startTime) + "s");
    	speed = 0.0;
    	increment = .005;
    	Robot.measurement.resetFlowMotion();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    	end();
    }
}
